### ISSUE TITLE
cannot manually check out workspace

### ISSUE THREAD

**Issue by christian-rauch** [jspricke/ros-deb-builder-action#46]
I am trying to manually check out a workspace, instead of using a repos file, to have better control over the branches that are used for packages. For this, I would do something like:
```yaml
- name: check out workspace
  run: |
    vcs import << EOF
    repositories:
      src/my_package:
        type: git
        url: https://github.com/my/package.git
        version: ${{ matrix.my_package_branch }}
    EOF

- name: debug file layout
  run: |
    pwd
    ls

- uses: jspricke/ros-deb-builder-action@main
```

In the CI log, I can see that the workspace is checked out:
```
/__w/camera-ros-deb-builder/camera-ros-deb-builder
src
```
but once `ros-deb-builder-action` runs, the workspace is deleted again:
```
Deleting the contents of '/__w/camera-ros-deb-builder/camera-ros-deb-builder'
```
hence it will not find the packages:
```
Workspace "/__w/camera-ros-deb-builder/camera-ros-deb-builder" seems to not contain any projects. Have you passed the correct path to a catkin workspace?+ colcon list --topological-order --names-only
```

I assume this is not a supported scenario? How should this be supported? Should there be an option to provide the path to a workspace? Or should it stay as is and the repos file should be generated dynamically?

Edit: Forget about the dynamically generated repos file. This will of course also be generated and deleted in the same folder. 

Any suggestions on how to build a manually checked-out workspace in the CI?

**Comment by jspricke** [comment]
> I am trying to manually check out a workspace, instead of using a repos file, to have better control over the branches that are used for packages. For this, I would do something like:

I think this should work already as you can also add the action to a ROS package and have no repos file.

> but once `ros-deb-builder-action` runs, the workspace is deleted again:
> 
> ```
> Deleting the contents of '/__w/camera-ros-deb-builder/camera-ros-deb-builder'
> ```

I don't think this action does that, at least I don't see something like that in the code. Can you send a link to a log?

**Comment by christian-rauch** [comment]
The log is at: https://github.com/christianrauch/camera-ros-deb-builder/actions/runs/8958147432/job/24602063328

The relevant parts of the raw log are:
```
##[group]Run jspricke/ros-deb-builder-action@main
with:
  DEB_DISTRO: jammy
  DEB_ARCH: arm64
  ROS_DISTRO: humble
  GITHUB_TOKEN: ***
  PACKAGES_BRANCH: jammy-humble-arm64-package-xml-0.1-strip
  SQUASH_HISTORY: false
##[endgroup]
##[group]Run actions/checkout@v3
with:
  repository: christianrauch/camera-ros-deb-builder
  token: ***
  ssh-strict: true
  persist-credentials: true
  clean: true
  sparse-checkout-cone-mode: true
  fetch-depth: 1
  fetch-tags: false
  lfs: false
  submodules: false
  set-safe-directory: true
##[endgroup]
##[command]/usr/bin/docker exec  12d304f079d2f86dc8339ee7419a640b04316f4173d4b2a76cf958e5b633be64 sh -c "cat /etc/*release | grep ^ID"
Syncing repository: christianrauch/camera-ros-deb-builder
##[group]Getting Git version info
Working directory is '/__w/camera-ros-deb-builder/camera-ros-deb-builder'
[command]/usr/bin/git version
git version 2.34.1
##[endgroup]
Temporarily overriding HOME='/__w/_temp/79ab858e-59b2-4962-99fa-878a078ef4a8' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
[command]/usr/bin/git config --global --add safe.directory /__w/camera-ros-deb-builder/camera-ros-deb-builder
Deleting the contents of '/__w/camera-ros-deb-builder/camera-ros-deb-builder'
##[group]Initializing the repository
[command]/usr/bin/git init /__w/camera-ros-deb-builder/camera-ros-deb-builder
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /__w/camera-ros-deb-builder/camera-ros-deb-builder/.git/
[command]/usr/bin/git remote add origin https://github.com/christianrauch/camera-ros-deb-builder
##[endgroup]
```
