### ISSUE TITLE
private git repo access

### ISSUE THREAD

**Issue by christian-rauch** [jspricke/ros-deb-builder-action#69]
I have a private "ros-deb-builder" CI repo that runs the `jspricke/ros-deb-builder-action` action with a `sources.repos` that includes a private repo, `https://github.com/$USER/$REPO.git`:
```yaml
repositories:
  src/$REPO:
    type: git
    url: https://github.com/$USER/$REPO.git
    version: main
```

In the CI workflow, I set up a GitHub token `REPO_TOKEN` via:
```yaml
- run: |
    git config --global credential.helper store
    echo "https://NONE:${{ secrets.REPO_TOKEN }}@github.com" > ~/.git-credentials
```

Using this token, I can clone the private repo:
```yaml
- run: git clone https://github.com/$USER/$REPO.git
```
as well as import the repo via vcs from the same `sources.repos` of the CI repo:
```yaml
- uses: actions/checkout@v4
- run: |
    pip install vcstool
    mkdir -p /tmp/src/
    vcs import --recursive --input sources.repos /tmp/src/
```

However, the `jspricke/ros-deb-builder-action` action with:
```yaml
- uses: jspricke/ros-deb-builder-action@main
  with:
    ROS_DISTRO: ${{ matrix.ros }}
    DEB_DISTRO: ${{ matrix.deb }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SBUILD_CONF: "$enable_network = 1;"
```
fails to import the repo with vcs:
```
+ vcs import --recursive --input sources.repos src
E.
=== src/src/$REPO (git) ===
Could not determine ref type of version: remote: Repository not found.
fatal: repository 'https://github.com/$USER/$REPO.git/' not found
```

Since the git config is global (`git config --global`), the `credential.helper` settings should apply to any git command ran by the action runner, including the `vcs import` inside the `ros-deb-builder-action` action.

I have the feeling this is a user error on my side and is missing some configuration. Any idea what I am doing wrong? The documentation only mentions the `GITHUB_TOKEN` for pushing the packages to the repo. Am I missing some undocumented configuration option?

**Comment by jspricke** [comment]
I am not convinced using `/tmp/ws` is a good idea (apart from that it should use `mktemp`). Currently you can run `build` inside a workspace to generate packages. I think this bug should be fixed in `vcstool` and maybe we can work around it in the mean time. Can you try renaming `.git` before running `vcstool`?

**Comment by christian-rauch** [comment]
> Can you try renaming `.git` before running `vcstool`?

Do you mean inside your action? The issue appears already without a manual checkout:
```yaml
steps:
  - run: |
      git config --global credential.helper store
      echo "https://NONE:${{ secrets.REPO_TOKEN }}@github.com" > ~/.git-credentials
  - uses: jspricke/ros-deb-builder-action@main
    with:
      ROS_DISTRO: ${{ matrix.ros }}
      DEB_DISTRO: ${{ matrix.deb }}
```
because the action already uses `actions/checkout@v4`.

Another workaround would probably checking out the repo in a `repo` subdir, e.g.:
```yaml
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      if: ${{ inputs.SKIP_CHECKOUT == 'false' }}
      with:
        path: "repo"
```
and then reading the `sources.repos` from there.

> Currently you can run `build` inside a workspace to generate packages.

This makes it quite convenient, but running this in a "polluted" working directory could have all kind of side effects. IMHO, it would be safer anyway to run the workspace checkout and the indexing isolated.
